# Generated by Django 5.2.1 on 2026-09-21 07:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0008_rename_bookings_bo_booking_1a2b3c_idx_bookings_bo_booking_147844_idx_and_more'),
        ('instant_bookings', '0006_instant_booking_no_provider_email_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingFeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fee_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED_AMOUNT', 'Fixed Amount')], default='FIXED_AMOUNT', max_length=20)),
                ('fee_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_type', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('INSTANT', 'Instant'), ('BOTH', 'Both')], default='BOTH', max_length=20)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['minimum_amount'],
            },
        ),
        migrations.CreateModel(
            name='PlatformFeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('minimum_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['minimum_amount'],
            },
        ),
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('service_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('extended_service_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('material_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('travel_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tip_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('booking_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fix_coin_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('business_gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('business_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('business_net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CALCULATED', 'Calculated'), ('PENDING_PAYMENT', 'Pending Payment'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('ADJUSTED', 'Adjusted'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded'), ('CANCELLED', 'Cancelled'), ('FINALIZED', 'Finalized')], db_index=True, default='DRAFT', max_length=30)),
                ('version', models.PositiveIntegerField(default=1)),
                ('calculation_snapshot', models.JSONField(blank=True, default=dict, help_text='A snapshot of all applied rules, rates, and parameters at the time of finalization.')),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_records', to='bookings.booking')),
                ('instant_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_records', to='instant_bookings.instantbooking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('item_type', models.CharField(choices=[('SERVICE', 'Service'), ('EXTENDED_SERVICE', 'Extended Service'), ('MATERIAL', 'Material'), ('TRAVEL', 'Travel'), ('TIP', 'Tip'), ('PLATFORM_FEE', 'Platform Fee'), ('BOOKING_FEE', 'Booking Fee'), ('TAX', 'Tax'), ('DISCOUNT', 'Discount'), ('FIX_COINS', 'Fix Coins'), ('ADJUSTMENT', 'Adjustment'), ('REFUND', 'Refund')], max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('line_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.billingrecord')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='billingrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('booking__isnull', False), ('instant_booking__isnull', True)), models.Q(('booking__isnull', True), ('instant_booking__isnull', False)), _connector='OR'), name='billing_record_exactly_one_booking_type'),
        ),
    ]
