# Generated by Django 5.2.1 on 2026-09-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('bookings', '0008_rename_bookings_bo_booking_1a2b3c_idx_bookings_bo_booking_147844_idx_and_more'),
        ('instant_bookings', '0006_instant_booking_no_provider_email_template'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='billingrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'DRAFT')), fields=('booking', 'status'), name='unique_draft_per_booking'),
        ),
        migrations.AddConstraint(
            model_name='billingrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'DRAFT')), fields=('instant_booking', 'status'), name='unique_draft_per_instant_booking'),
        ),
    ]
