# Generated by Django 5.2.1 on 2026-09-15 06:33

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FixCoinSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins_per_rupee', models.PositiveIntegerField(default=10, help_text='Number of Fix-Coins equivalent to 1 INR (e.g. 10 coins = ₹1)', validators=[django.core.validators.MinValueValidator(1)])),
                ('signup_bonus_coins', models.PositiveIntegerField(default=500, help_text='Bonus coins awarded upon successful new user verification', validators=[django.core.validators.MinValueValidator(0)])),
                ('reward_coins_per_100_rupees', models.PositiveIntegerField(default=10, help_text='Coins earned per ₹100 of eligible spend', validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_redemption_coins', models.PositiveIntegerField(default=100, help_text='Minimum coins required to execute a redemption', validators=[django.core.validators.MinValueValidator(0)])),
                ('maximum_redemption_percentage', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Maximum percentage of eligible booking value that can be paid via coins', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('expiry_days', models.PositiveIntegerField(default=180, help_text='Default days until credited coins expire', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Designates if this configuration is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fix-Coin Setting',
                'verbose_name_plural': 'Fix-Coin Settings',
            },
        ),
        migrations.CreateModel(
            name='FixCoinWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('available_coins', models.PositiveIntegerField(default=0, help_text='Current spendable Fix-Coins balance')),
                ('lifetime_earned_coins', models.PositiveIntegerField(default=0, help_text='Total coins ever credited')),
                ('lifetime_redeemed_coins', models.PositiveIntegerField(default=0, help_text='Total coins ever debited via redemption')),
                ('lifetime_expired_coins', models.PositiveIntegerField(default=0, help_text='Total coins expired')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fix_coin_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fix-Coin Wallet',
                'verbose_name_plural': 'Fix-Coin Wallets',
            },
        ),
        migrations.CreateModel(
            name='FixCoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('SIGNUP_BONUS', 'Signup Bonus'), ('BOOKING_REWARD', 'Booking Reward'), ('REDEMPTION', 'Redemption'), ('REFUND_REVERSAL', 'Refund Reversal'), ('EXPIRY', 'Expiry'), ('PROMOTIONAL_BONUS', 'Promotional Bonus'), ('ADMIN_ADJUSTMENT', 'Admin Adjustment')], db_index=True, max_length=32)),
                ('coins', models.IntegerField(help_text='Delta in coins: positive for credit, negative for debit')),
                ('balance_before', models.PositiveIntegerField(help_text='Wallet available coins before transaction')),
                ('balance_after', models.PositiveIntegerField(help_text='Wallet available coins after transaction')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('reference_type', models.CharField(blank=True, choices=[('SIGNUP', 'Signup'), ('BOOKING', 'Booking'), ('PAYMENT', 'Payment'), ('REFUND', 'Refund'), ('PROMOTION', 'Promotion'), ('ADMIN', 'Admin')], db_index=True, help_text='Type of related entity (e.g. SIGNUP, BOOKING, PAYMENT)', max_length=32, null=True)),
                ('reference_id', models.CharField(blank=True, db_index=True, help_text='Identifier of related entity (UUID, booking ID, etc.)', max_length=128, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when credited coins expire', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='fix_coins.fixcoinwallet')),
            ],
            options={
                'verbose_name': 'Fix-Coin Transaction',
                'verbose_name_plural': 'Fix-Coin Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='fixcoinwallet',
            constraint=models.CheckConstraint(condition=models.Q(('available_coins__gte', 0)), name='fix_coin_wallet_available_coins_gte_0'),
        ),
        migrations.AddIndex(
            model_name='fixcointransaction',
            index=models.Index(fields=['wallet', 'created_at'], name='fix_coins_f_wallet__936d21_idx'),
        ),
        migrations.AddIndex(
            model_name='fixcointransaction',
            index=models.Index(fields=['reference_type', 'reference_id'], name='fix_coins_f_referen_882429_idx'),
        ),
        migrations.AddIndex(
            model_name='fixcointransaction',
            index=models.Index(fields=['transaction_type', 'wallet'], name='fix_coins_f_transac_473d0a_idx'),
        ),
    ]
