# Generated by Django 5.2.1 on 2026-09-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fix_coins', '0002_backfill_existing_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixcoinwallet',
            name='reserved_coins',
            field=models.PositiveIntegerField(default=0, help_text='Coins reserved for pending bookings'),
        ),
        migrations.AlterField(
            model_name='fixcointransaction',
            name='transaction_type',
            field=models.CharField(choices=[('SIGNUP_BONUS', 'Signup Bonus'), ('BOOKING_REWARD', 'Booking Reward'), ('REDEMPTION', 'Redemption'), ('REFUND_REVERSAL', 'Refund Reversal'), ('EXPIRY', 'Expiry'), ('RESERVATION', 'Reservation'), ('RELEASE', 'Release'), ('PROMOTIONAL_BONUS', 'Promotional Bonus'), ('ADMIN_ADJUSTMENT', 'Admin Adjustment')], db_index=True, max_length=32),
        ),
    ]
