# Generated by Django 5.2.1 on 2026-09-21 07:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('VOID', 'Void')], default='ISSUED', max_length=20)),
                ('company_name', models.CharField(default='TodayFix Inc.', max_length=255)),
                ('company_address', models.TextField(default='123 Platform Way')),
                ('company_gstin', models.CharField(default='29ABCDE1234F1Z5', max_length=20)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('customer_address', models.TextField(blank=True, default='')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('pdf_url', models.URLField(blank=True, default='', max_length=500)),
                ('billing_record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='billing.billingrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='invoices.invoice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
