# Generated by Django 5.2.1 on 2026-09-21 07:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('REFUND', 'Refund'), ('ADJUST', 'Adjust'), ('APPROVE', 'Approve'), ('CANCEL', 'Cancel')], db_index=True, max_length=50)),
                ('object_type', models.CharField(db_index=True, help_text="The type of the object being modified (e.g. 'Payout', 'FinanceAccount', 'FixCoinWallet').", max_length=100)),
                ('object_id', models.CharField(db_index=True, help_text='The unique identifier (UUID or ID) of the modified object.', max_length=255)),
                ('old_state', models.JSONField(blank=True, default=dict, help_text='The state of the object before the modification.')),
                ('new_state', models.JSONField(blank=True, default=dict, help_text='The state of the object after the modification.')),
                ('reason', models.TextField(blank=True, default='', help_text='Why this action was performed (especially important for manual adjustments).')),
                ('request_id', models.CharField(blank=True, db_index=True, default='', help_text='Optional ID mapping to the external request or idempotent request ID.', max_length=255)),
                ('actor', models.ForeignKey(blank=True, help_text='User/Admin who performed the action. Null if system.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', 'action'], name='finance_fin_actor_i_79f9b6_idx'), models.Index(fields=['object_type', 'object_id'], name='finance_fin_object__598fb1_idx')],
            },
        ),
    ]
