# Generated by Django 5.2.1 on 2026-09-21 07:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('account_type', models.CharField(choices=[('PLATFORM', 'Platform'), ('BUSINESS', 'Business'), ('CUSTOMER', 'Customer')], max_length=20)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lifetime_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lifetime_withdrawn', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('entry_type', models.CharField(choices=[('CUSTOMER_PAYMENT', 'Customer Payment'), ('BUSINESS_EARNING', 'Business Earning'), ('PLATFORM_FEE', 'Platform Fee'), ('BOOKING_FEE', 'Booking Fee'), ('REFUND', 'Refund'), ('REFUND_REVERSAL', 'Refund Reversal'), ('PAYOUT', 'Payout'), ('PAYOUT_REVERSAL', 'Payout Reversal'), ('TAX', 'Tax'), ('ADJUSTMENT', 'Adjustment')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_id', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_available', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='finance.financeaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='financeaccount',
            constraint=models.CheckConstraint(condition=models.Q(('account_type', 'PLATFORM'), ('user__isnull', False), _connector='OR'), name='finance_account_user_required_unless_platform'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['reference_id'], name='finance_led_referen_749548_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['account', 'entry_type'], name='finance_led_account_a6df32_idx'),
        ),
    ]
