# Generated by Django 6.0.8 on 2026-09-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_searchlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.CharField(db_index=True, help_text="A word users might search for, e.g. 'putting'.", max_length=100)),
                ('synonym', models.CharField(db_index=True, help_text="The word it should also match, e.g. 'installation'. Matching works both ways.", max_length=100)),
            ],
            options={
                'ordering': ['term'],
                'constraints': [models.UniqueConstraint(fields=('term', 'synonym'), name='unique_search_synonym_pair')],
            },
        ),
    ]
