# Generated by Django 5.2.6 on 2026-09-08 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_searchsynonym'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='service',
            name='unit',
        ),
    ]
