# Generated by Django 5.2.6 on 2026-09-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_service_service_type_remove_service_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='rank',
            field=models.PositiveIntegerField(db_index=True, default=1, help_text="Priority rank used to order this service in search results and browsing. Higher rank is shown first, with the business's rank used as a tiebreaker. Currently set manually by admin; a future automated system may raise it based on search appearances, bookings, and clicks — this field is intentionally left unconstrained (no uniqueness, no max) so that future increment logic won't error."),
        ),
    ]
