# Generated by Django 6.0.8 on 2026-08-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_googleidentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('SIGNUP', 'Signup'), ('LOGIN', 'Login'), ('PHONE_UPDATE', 'Phone Update')], db_index=True, default='SIGNUP', max_length=20),
        ),
    ]
