# Generated by Django 5.2.6 on 2026-08-06 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(db_index=True, max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in E.164 format. Example: +919876543210', regex='^\\+[1-9]\\d{7,14}$')], verbose_name='Phone Number'),
        ),
    ]
    
