# Generated by Django 6.0.8 on 2026-08-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_otpverification_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='location',
            field=models.CharField(blank=True, help_text='Google Maps iframe/embed location.', max_length=2000, null=True),
        ),
    ]
