# Generated by Django 5.2.6 on 2026-08-06 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_business_verified_customuser_has_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(db_index=True, max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits and start with 6, 7, 8, or 9.', regex='^[6-9]\\d{9}$')], verbose_name='Phone Number'),
        ),
    ]
    
