# Generated by Django 5.2.6 on 2026-08-11 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_passwordresetotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetVerificationToken',
        ),
    ]
