# Generated by Django 5.2.1 on 2026-09-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_registration_verification_password_reset_email_templates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpverification',
            old_name='provider_request_id',
            new_name='external_request_id',
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='provider',
            field=models.CharField(db_index=True, default='SMS', max_length=30),
        ),
    ]
