# Generated by Django 6.0.8 on 2026-09-18 08:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_email_update_verification_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_user_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('original_user_uuid', models.UUIDField(db_index=True)),
                ('original_user_id', models.PositiveBigIntegerField(db_index=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('role', models.CharField(blank=True, default='', max_length=20)),
                ('has_business', models.BooleanField(default=False)),
                ('business_verified', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('account_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-deleted_at'],
            },
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('SIGNUP', 'Signup'), ('LOGIN', 'Login'), ('PHONE_UPDATE', 'Phone Update'), ('ACCOUNT_DELETION', 'Account Deletion')], db_index=True, default='SIGNUP', max_length=20),
        ),
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_deletion_request_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_deletion_at', models.DateTimeField()),
                ('hold_started_at', models.DateTimeField(blank=True, null=True)),
                ('extension_deadline', models.DateTimeField(blank=True, null=True)),
                ('condition_cleared_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_deletion_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
