# Generated by Django 6.0.8 on 2026-09-18 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_account_deletion_email_templates'),
        ('accounts', '0011_deleteduser_alter_otpverification_purpose_and_more'),
    ]

    operations = [
    ]
