"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.8.
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv


# ============================================================
# BASE CONFIGURATION
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env", override=False)


# ============================================================
# SECURITY
# ============================================================

SECRET_KEY = os.getenv("SECRET_KEY")

GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")

DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = ["*"]


# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party apps
    "rest_framework",
    "drf_spectacular",
    "rest_framework_simplejwt.token_blacklist",
    "django_filters",

    # Local apps
    "accounts",
    "business",
    "categories",
    "services",
    "bookings",
    "instant_bookings",
    "chat_service",
    "calling_service",
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ============================================================
# URL / WSGI
# ============================================================

ROOT_URLCONF = "core.urls"

WSGI_APPLICATION = "core.wsgi.application"


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ============================================================
# DATABASE
# ============================================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",

        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),

        # IMPORTANT:
        # In Docker this should normally be the PostgreSQL
        # service name, e.g. "db", NOT "localhost".
        "HOST": os.getenv("DB_HOST", "localhost"),

        "PORT": int(os.getenv("DB_PORT", "5432")),

        "CONN_MAX_AGE": 60,
    }
}


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME":
            "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME":
            "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME":
            "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME":
            "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]



AUTH_USER_MODEL = "accounts.CustomUser"
AUTHENTICATION_BACKENDS = [
    "accounts.backends.EmailOrPhoneBackend",
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = "/static/"

# Source static files
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Generated static files
# Used by `python manage.py collectstatic`
STATIC_ROOT = BASE_DIR / "staticfiles"

# ============================================================
# MEDIA / FILE STORAGE
# ============================================================

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "temp"


# ============================================================
# REST FRAMEWORK
# ============================================================

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS":
        "drf_spectacular.openapi.AutoSchema",

    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,

    "DEFAULT_AUTHENTICATION_CLASSES": (
        "accounts.authentication.CustomJWTAuthentication",
    ),

    "EXCEPTION_HANDLER": "common.exception_handlers.custom_exception_handler",
}


# ============================================================
# JWT / OPENAPI
# ============================================================

from drf_spectacular.extensions import OpenApiAuthenticationExtension


def rename_stray_tags(result, generator, request, public):
    """
    Postprocessing hook: folds any operation tagged with a stray/auto-detected
    tag name (e.g. endpoints that forgot an explicit @extend_schema(tags=[...]))
    into a proper tag, and drops the stray tag from the tag list shown in
    Swagger UI. Add more entries to rename_map as you find more strays.
    """
    rename_map = {
        "auth": "Login",
    }

    for path_item in result.get("paths", {}).values():
        for operation in path_item.values():
            if isinstance(operation, dict) and "tags" in operation:
                operation["tags"] = [
                    rename_map.get(tag, tag) for tag in operation["tags"]
                ]

    result["tags"] = [
        tag for tag in result.get("tags", [])
        if tag["name"] not in rename_map
    ]

    return result


SPECTACULAR_SETTINGS = {
    "TITLE": "TodayFix Service API",
    "DESCRIPTION": "TodayFix.in Backend Service APIs",
    "VERSION": "1.0.0",
    "DEFAULT_GENERATOR_CLASS": "core.schema.TodayFixSchemaGenerator",

    "SERVE_INCLUDE_SCHEMA": False,

    # NOTE: these names must exactly match the strings used in each view's
    # @extend_schema(tags=[...]). A tag listed here with no matching
    # operation simply won't show up; an operation tagged with a name not
    # listed here will still appear, just appended after these in
    # auto-discovery order instead of the order defined below.
    "TAGS": [
        {
            "name": "SignUp",
            "description":
                "User registration and OTP verification.",
        },
        {
            "name": "Login",
            "description":
                "Login, OTP login, and Google login.",
        },
        {
            "name": "Logout",
            "description":
                "Session/token logout.",
        },
        {
            "name": "Accounts",
            "description":
                "Authenticated user profile management.",
        },
        {
            "name": "Address",
            "description":
                "Authenticated user address management.",
        },
        {
            "name": "Business Application",
            "description":
                "Submit and manage business upgrade applications.",
        },
        {
            "name": "Business Upgrade Request",
            "description":
                "Business upgrade request workflow.",
        },
        {
            "name": "Business Administration",
            "description":
                "Admin review, approval and rejection of business applications.",
        },
        {
            "name": "Business Profile",
            "description":
                "Business profile management.",
        },
        {
            "name": "Business Employees",
            "description":
                "Business employee management.",
        },
        {
            "name": "Service Provider Availability",
            "description":
                "Provider availability management.",
        },
        {
            "name": "Provider Working Schedule",
            "description":
                "Provider working schedule management.",
        },
        {
            "name": "Categories",
            "description":
                "Service category management.",
        },
        {
            "name": "SubCategories",
            "description":
                "Service subcategory management.",
        },

        {
            "name": "SubCategories",
            "description":
                "Service subcategory management.",
        },
        {
            "name": "Chat - Service",
            "description":
                "In-app chat conversations and messages.",
        },
        {
            "name": "Calling - Service",
            "description":
                "Audio/video call session management.",
        },
        {
            "name": "Services",
            "description":
                "Service catalog and business service management.",
        },
        {
            "name": "Services",
            "description":
                "Service catalog and business service management.",
        },
        {
            "name": "Service Types",
            "description":
                "Service type management.",
        },
        {
            "name": "Units",
            "description":
                "Service unit management.",
        },
        {
            "name": "Scheduled Bookings",
            "description":
                "User and business scheduled booking management.",
        },
        {
            "name": "Booking History",
            "description":
                "Booking history.",
        },
        {
            "name": "Instant Bookings",
            "description":
                "Instant booking management.",
        },
    ],

    "SECURITY": [
        {
            "BearerAuth": [],
        }
    ],

    "POSTPROCESSING_HOOKS": [
        "drf_spectacular.hooks.postprocess_schema_enums",
        "core.settings.rename_stray_tags",
    ],
}





class JWTAuthenticationScheme(OpenApiAuthenticationExtension):
    target_class = "accounts.authentication.CustomJWTAuthentication"
    name = "BearerAuth"

    def get_security_definition(self, auto_schema):
        return {
            "type": "http",
            "scheme": "bearer",
            "bearerFormat": "JWT",
        }





# ============================================================
# DEFAULT PRIMARY KEY
# ============================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ============================================================
# JWT
# ============================================================

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),

    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),

    "ROTATE_REFRESH_TOKENS": True,

    "BLACKLIST_AFTER_ROTATION": True,
}


# ============================================================
# EMAIL
# ============================================================

DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    "noreply@todayfix.com",
)

FRONTEND_DOMAIN = os.getenv(
    "FRONTEND_DOMAIN",
    "http://localhost:3000",
)

FRONTEND_RESET_PASSWORD_URL = (
    f"{FRONTEND_DOMAIN}/reset-password/"
)

EMAIL_HOST = os.getenv("EMAIL_HOST")

EMAIL_PORT = int(
    os.getenv("EMAIL_PORT", "587")
)

EMAIL_USE_TLS = (
    os.getenv("EMAIL_USE_TLS", "True") == "True"
)

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")

EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")

EMAIL_LOGO_URL = (
    f"{FRONTEND_DOMAIN}/static/images/todayfix-logo.png"
)


# ============================================================
# FAST2SMS
# ============================================================

FAST2SMS_API_KEY = os.getenv(
    "FAST2SMS_API_KEY",
    "",
)