# Generated by Django 5.2.1 on 2026-09-21 07:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('report_date', models.DateField(unique=True)),
                ('total_expected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_settled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_transactions_count', models.IntegerField(default=0)),
                ('settled_transactions_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('MATCHED', 'Matched'), ('DISCREPANCY', 'Discrepancy')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
    ]
