# Generated by Django 5.2.1 on 2026-09-21 07:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('account_type', models.CharField(choices=[('BANK_ACCOUNT', 'Bank Account'), ('UPI', 'UPI')], default='BANK_ACCOUNT', max_length=20)),
                ('account_number', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(blank=True, default='', max_length=20)),
                ('upi_id', models.CharField(blank=True, default='', max_length=100)),
                ('beneficiary_name', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payout_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('payout_type', models.CharField(choices=[('WEEKLY', 'Weekly'), ('EMERGENCY', 'Emergency')], default='WEEKLY', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reference_id', models.CharField(blank=True, default='', help_text='Gateway payout ID', max_length=100)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to=settings.AUTH_USER_MODEL)),
                ('payout_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payouts.payoutaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
