# Generated by Django 6.0.8 on 2026-08-27 11:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_otpverification_purpose'),
        ('business', '0003_alter_businessidentity_aadhaar_document_and_more'),
        ('categories', '0002_subcategory_image'),
        ('services', '0003_backfill_service_type_and_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstantBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instant_booking_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('requested_service_name', models.CharField(help_text='The service selected/requested by the customer.', max_length=255)),
                ('customer_note', models.TextField(blank=True, default='')),
                ('average_service_price', models.DecimalField(decimal_places=2, default=0, help_text='Average price of matching services in the selected distance band.', max_digits=10)),
                ('travel_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quoted_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('search_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('QUOTED', 'Quoted'), ('SEARCHING', 'Searching for provider'), ('ASSIGNED', 'Provider assigned'), ('NO_PROVIDER', 'No provider found'), ('CANCELLED', 'Cancelled'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], db_index=True, default='QUOTED', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Time after which outstanding provider offers are no longer valid.', null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instant_bookings', to='accounts.address')),
                ('assigned_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_instant_bookings', to='business.businessprofile')),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_instant_bookings', to='business.employee')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instant_bookings', to='categories.category')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instant_bookings', to=settings.AUTH_USER_MODEL)),
                ('selected_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_instant_bookings', to='services.service')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instant_bookings', to='categories.subcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstantBookingOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estimated_travel_minutes', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instant_booking_offers', to='business.businessprofile')),
                ('employee', models.ForeignKey(blank=True, help_text='Null for an individual business owner; set for company/investor employees.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instant_booking_offers', to='business.employee')),
                ('instant_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_offers', to='instant_bookings.instantbooking')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instant_booking_offers', to='services.service')),
            ],
            options={
                'ordering': ['distance_km', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstantBookingPricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('minimum_distance_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('maximum_distance_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('travel_fee_per_km', models.DecimalField(decimal_places=2, default=0, help_text='Travel fee charged per kilometre after the minimum distance of this rule.', max_digits=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['minimum_distance_km'],
                'constraints': [models.UniqueConstraint(fields=('minimum_distance_km', 'maximum_distance_km'), name='unique_instant_booking_distance_band')],
            },
        ),
        migrations.AddIndex(
            model_name='instantbooking',
            index=models.Index(fields=['customer', 'status'], name='instant_boo_custome_fe3d19_idx'),
        ),
        migrations.AddIndex(
            model_name='instantbooking',
            index=models.Index(fields=['status', 'expires_at'], name='instant_boo_status_e1291d_idx'),
        ),
        migrations.AddIndex(
            model_name='instantbooking',
            index=models.Index(fields=['category', 'subcategory'], name='instant_boo_categor_b3601c_idx'),
        ),
        migrations.AddIndex(
            model_name='instantbookingoffer',
            index=models.Index(fields=['instant_booking', 'status'], name='instant_boo_instant_e7f85f_idx'),
        ),
        migrations.AddIndex(
            model_name='instantbookingoffer',
            index=models.Index(fields=['business', 'status'], name='instant_boo_busines_c906be_idx'),
        ),
        migrations.AddIndex(
            model_name='instantbookingoffer',
            index=models.Index(fields=['employee', 'status'], name='instant_boo_employe_673fdb_idx'),
        ),
    ]
