# Generated by Django 6.0.8 on 2026-08-27 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_businessidentity_aadhaar_document_and_more'),
        ('categories', '0002_subcategory_image'),
        ('instant_bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instantbooking',
            name='average_service_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='instantbooking',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instant_bookings', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='instantbooking',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instantbooking',
            name='requested_service_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='instantbooking',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instant_bookings', to='categories.subcategory'),
        ),
        migrations.AlterField(
            model_name='instantbookingoffer',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instant_booking_offers', to='business.employee'),
        ),
        migrations.AlterField(
            model_name='instantbookingpricingrule',
            name='travel_fee_per_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='instantbookingpricingrule',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_distance_km__gt', models.F('minimum_distance_km'))), name='valid_instant_booking_distance_band'),
        ),
        migrations.AddConstraint(
            model_name='instantbookingpricingrule',
            constraint=models.CheckConstraint(condition=models.Q(('platform_fee__gte', 0)), name='non_negative_instant_platform_fee'),
        ),
        migrations.AddConstraint(
            model_name='instantbookingpricingrule',
            constraint=models.CheckConstraint(condition=models.Q(('travel_fee_per_km__gte', 0)), name='non_negative_instant_travel_fee'),
        ),
    ]
