# Generated by Django 6.0.8 on 2026-08-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instant_bookings', '0002_alter_instantbooking_average_service_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instantbooking',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='instantbooking',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='instantbookingpricingrule',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST percentage applied to subtotal.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='instantbooking',
            name='status',
            field=models.CharField(choices=[('QUOTED', 'Quoted'), ('SEARCHING', 'Searching for provider'), ('ASSIGNED', 'Provider assigned'), ('CANCELLED', 'Cancelled'), ('NO_PROVIDER', 'No provider found'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], db_index=True, default='QUOTED', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='instantbookingpricingrule',
            constraint=models.CheckConstraint(condition=models.Q(('gst_percentage__gte', 0)), name='non_negative_instant_gst_percentage'),
        ),
    ]
