# Generated by Django 6.0.8 on 2026-08-28 07:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_address_location'),
        ('business', '0004_alter_businessprofile_location'),
        ('categories', '0002_subcategory_image'),
        ('instant_bookings', '0003_instantbooking_gst_amount_and_more'),
        ('services', '0003_backfill_service_type_and_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instantbooking',
            name='offer_round',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='instantbooking',
            name='search_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instantbooking',
            name='tip_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='instantbooking',
            name='total_payable_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='instantbooking',
            name='status',
            field=models.CharField(choices=[('QUOTED', 'Quoted'), ('SEARCHING', 'Searching for provider'), ('TIP_REQUIRED', 'Tip required'), ('ASSIGNED', 'Provider assigned'), ('CANCELLED', 'Cancelled'), ('NO_PROVIDER', 'No provider found'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], db_index=True, default='QUOTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='instantbookingpricingrule',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST percentage applied to the subtotal.', max_digits=5),
        ),
        migrations.AddIndex(
            model_name='instantbooking',
            index=models.Index(fields=['status', 'search_deadline'], name='instant_boo_status_df89e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='instantbooking',
            constraint=models.CheckConstraint(condition=models.Q(('tip_amount__gte', 0)), name='non_negative_instant_tip'),
        ),
        migrations.AddConstraint(
            model_name='instantbooking',
            constraint=models.CheckConstraint(condition=models.Q(('quoted_price__gte', 0)), name='non_negative_instant_quoted_price'),
        ),
        migrations.AddConstraint(
            model_name='instantbooking',
            constraint=models.CheckConstraint(condition=models.Q(('total_payable_price__gte', 0)), name='non_negative_instant_total_price'),
        ),
    ]
