# Generated by Django 6.0.8 on 2026-08-21 06:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_application_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('business_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company'), ('INVESTOR', 'Investor')], db_index=True, max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_applications', to='categories.category')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_business_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_bank_account_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('account_holder_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('bank_name', models.CharField(max_length=150)),
                ('branch_name', models.CharField(blank=True, default='', max_length=150)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='business.businessapplication')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_business_bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_identity_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('pan_number', models.CharField(blank=True, default='', max_length=10)),
                ('pan_document', models.BinaryField(blank=True, null=True)),
                ('pan_document_name', models.CharField(blank=True, default='', max_length=255)),
                ('pan_document_type', models.CharField(blank=True, default='', max_length=100)),
                ('aadhaar_number', models.CharField(blank=True, default='', max_length=12)),
                ('aadhaar_document', models.BinaryField(blank=True, null=True)),
                ('aadhaar_document_name', models.CharField(blank=True, default='', max_length=255)),
                ('aadhaar_document_type', models.CharField(blank=True, default='', max_length=100)),
                ('gst_number', models.CharField(blank=True, default='', max_length=15)),
                ('udyam_number', models.CharField(blank=True, default='', max_length=50)),
                ('labour_license_number', models.CharField(blank=True, default='', max_length=100)),
                ('bbmp_license_number', models.CharField(blank=True, default='', max_length=100)),
                ('food_license_number', models.CharField(blank=True, default='', max_length=100)),
                ('internal_store_photo', models.BinaryField(blank=True, null=True)),
                ('internal_store_name', models.CharField(blank=True, default='', max_length=255)),
                ('internal_store_type', models.CharField(blank=True, default='', max_length=100)),
                ('external_store_photo', models.BinaryField(blank=True, null=True)),
                ('external_store_name', models.CharField(blank=True, default='', max_length=255)),
                ('external_store_type', models.CharField(blank=True, default='', max_length=100)),
                ('cancelled_gst_bill_book_photo', models.BinaryField(blank=True, null=True)),
                ('cancelled_gst_bill_book_name', models.CharField(blank=True, default='', max_length=255)),
                ('cancelled_gst_bill_book_type', models.CharField(blank=True, default='', max_length=100)),
                ('logo', models.BinaryField(blank=True, null=True)),
                ('logo_name', models.CharField(blank=True, default='', max_length=255)),
                ('logo_type', models.CharField(blank=True, default='', max_length=100)),
                ('website', models.URLField(blank=True, default='')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity', to='business.businessapplication')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('business_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company'), ('INVESTOR', 'Investor')], db_index=True, max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_profiles', to='categories.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_profiles', to=settings.AUTH_USER_MODEL)),
                ('subcategories', models.ManyToManyField(blank=True, related_name='business_profiles', to='categories.subcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='business.businessprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeWorkingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_working_schedule_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10)),
                ('slot_type', models.CharField(choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('EVENING', 'Evening')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_schedules', to='business.businessprofile')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_schedules', to='business.employee')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ProviderAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_availability_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('BUSY', 'Busy')], db_index=True, default='AVAILABLE', max_length=20)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_availabilities', to='business.businessprofile')),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_availability', to='business.employee')),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_availability', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provider Availability',
                'verbose_name_plural': 'Provider Availabilities',
            },
        ),
        migrations.AddConstraint(
            model_name='businessapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('user',), name='unique_pending_business_application'),
        ),
        migrations.AddIndex(
            model_name='businessidentity',
            index=models.Index(fields=['pan_number'], name='business_bu_pan_num_6712bf_idx'),
        ),
        migrations.AddIndex(
            model_name='businessidentity',
            index=models.Index(fields=['gst_number'], name='business_bu_gst_num_2c3f32_idx'),
        ),
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['owner', 'business_type'], name='business_bu_owner_i_e0582f_idx'),
        ),
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['name'], name='business_bu_name_de3a17_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('business', 'phone'), name='unique_employee_phone_per_business'),
        ),
        migrations.AddConstraint(
            model_name='employeeworkingschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner', 'day_of_week', 'slot_type'), name='unique_owner_schedule_slot'),
        ),
        migrations.AddConstraint(
            model_name='employeeworkingschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('employee__isnull', False)), fields=('employee', 'day_of_week', 'slot_type'), name='unique_employee_schedule_slot'),
        ),
        migrations.AddConstraint(
            model_name='provideravailability',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('employee__isnull', True), ('owner__isnull', False)), models.Q(('employee__isnull', False), ('owner__isnull', True)), _connector='OR'), name='provider_availability_one_provider'),
        ),
    ]
