# Generated by Django 6.0.8 on 2026-08-18 15:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_application_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('business_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company'), ('INVESTOR', 'Investor')], db_index=True, max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_applications', to='categories.category')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_business_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_bank_account_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('account_holder_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('bank_name', models.CharField(max_length=150)),
                ('branch_name', models.CharField(blank=True, default='', max_length=150)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='business.businessapplication')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_business_bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_identity_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('pan_number', models.CharField(blank=True, default='', max_length=10)),
                ('pan_document', models.FileField(blank=True, null=True, upload_to='business/applications/pan/')),
                ('aadhaar_number', models.CharField(blank=True, default='', max_length=12)),
                ('aadhaar_document', models.FileField(blank=True, null=True, upload_to='business/applications/aadhaar/')),
                ('gst_number', models.CharField(blank=True, default='', max_length=15)),
                ('udyam_number', models.CharField(blank=True, default='', max_length=50)),
                ('labour_license_number', models.CharField(blank=True, default='', max_length=100)),
                ('bbmp_license_number', models.CharField(blank=True, default='', max_length=100)),
                ('food_license_number', models.CharField(blank=True, default='', max_length=100)),
                ('internal_store_photo', models.ImageField(blank=True, null=True, upload_to='business/applications/store/internal/')),
                ('external_store_photo', models.ImageField(blank=True, null=True, upload_to='business/applications/store/external/')),
                ('cancelled_gst_bill_book_photo', models.ImageField(blank=True, null=True, upload_to='business/applications/store/cancelled-bill/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business/applications/logos/')),
                ('website', models.URLField(blank=True, default='')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity', to='business.businessapplication')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('business_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company'), ('INVESTOR', 'Investor')], db_index=True, max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_profiles', to='categories.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_profiles', to=settings.AUTH_USER_MODEL)),
                ('subcategories', models.ManyToManyField(blank=True, related_name='business_profiles', to='categories.subcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='businessapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('user',), name='unique_pending_business_application'),
        ),
        migrations.AddIndex(
            model_name='businessidentity',
            index=models.Index(fields=['pan_number'], name='business_bu_pan_num_6712bf_idx'),
        ),
        migrations.AddIndex(
            model_name='businessidentity',
            index=models.Index(fields=['gst_number'], name='business_bu_gst_num_2c3f32_idx'),
        ),
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['owner', 'business_type'], name='business_bu_owner_i_e0582f_idx'),
        ),
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['name'], name='business_bu_name_de3a17_idx'),
        ),
    ]
