# Generated by Django 5.2.6 on 2026-08-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessidentity',
            name='aadhaar_document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='businessidentity',
            name='cancelled_gst_bill_book_photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='businessidentity',
            name='external_store_photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='businessidentity',
            name='internal_store_photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='businessidentity',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='businessidentity',
            name='pan_document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
