# Generated by Django 5.2.6 on 2026-08-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_businessidentity_aadhaar_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessidentity',
            name='aadhaar_document',
            field=models.FileField(blank=True, null=True, upload_to='business_applications/aadhaar/'),
        ),
        migrations.AlterField(
            model_name='businessidentity',
            name='cancelled_gst_bill_book_photo',
            field=models.FileField(blank=True, null=True, upload_to='business_applications/gst_bill_book/'),
        ),
        migrations.AlterField(
            model_name='businessidentity',
            name='external_store_photo',
            field=models.FileField(blank=True, null=True, upload_to='business_applications/store/external/'),
        ),
        migrations.AlterField(
            model_name='businessidentity',
            name='internal_store_photo',
            field=models.FileField(blank=True, null=True, upload_to='business_applications/store/internal/'),
        ),
        migrations.AlterField(
            model_name='businessidentity',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='business_applications/logo/'),
        ),
        migrations.AlterField(
            model_name='businessidentity',
            name='pan_document',
            field=models.FileField(blank=True, null=True, upload_to='business_applications/pan/'),
        ),
    ]
