# Generated by Django 6.0.8 on 2026-08-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_businessidentity_aadhaar_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='location',
            field=models.CharField(help_text='Google Maps iframe/embed location.', max_length=2000),
        ),
    ]
