# Generated by Django 6.0.8 on 2026-09-02 06:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_businessprofile_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUpgradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_upgrade_request_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('current_business_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company'), ('INVESTOR', 'Investor')], max_length=20)),
                ('requested_business_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company'), ('INVESTOR', 'Investor')], max_length=20)),
                ('keep_employees_and_schedules', models.BooleanField(blank=True, null=True)),
                ('bank_details_changed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_requests', to='business.businessprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_business_upgrade_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessUpgradeIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_upgrade_identity_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('pan_number', models.CharField(blank=True, default='', max_length=10)),
                ('pan_document', models.FileField(blank=True, null=True, upload_to='business_upgrade_requests/pan/')),
                ('aadhaar_number', models.CharField(blank=True, default='', max_length=12)),
                ('aadhaar_document', models.FileField(blank=True, null=True, upload_to='business_upgrade_requests/aadhaar/')),
                ('gst_number', models.CharField(blank=True, default='', max_length=15)),
                ('udyam_number', models.CharField(blank=True, default='', max_length=50)),
                ('labour_license_number', models.CharField(blank=True, default='', max_length=100)),
                ('bbmp_license_number', models.CharField(blank=True, default='', max_length=100)),
                ('food_license_number', models.CharField(blank=True, default='', max_length=100)),
                ('internal_store_photo', models.FileField(blank=True, null=True, upload_to='business_upgrade_requests/store/internal/')),
                ('external_store_photo', models.FileField(blank=True, null=True, upload_to='business_upgrade_requests/store/external/')),
                ('cancelled_gst_bill_book_photo', models.FileField(blank=True, null=True, upload_to='business_upgrade_requests/gst_bill_book/')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity', to='business.businessupgraderequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='businessupgraderequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('business',), name='unique_pending_business_upgrade_request'),
        ),
    ]
