# Generated by Django 6.0.8 on 2026-09-02 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_businessupgradebankaccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessupgradebankaccount',
            options={},
        ),
        migrations.RemoveField(
            model_name='businessupgradebankaccount',
            name='business_upgrade_bank_account_uuid',
        ),
        migrations.RemoveField(
            model_name='businessupgradebankaccount',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='businessupgradebankaccount',
            name='verification_status',
        ),
        migrations.RemoveField(
            model_name='businessupgradebankaccount',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='businessupgradebankaccount',
            name='verified_by',
        ),
    ]
