# Generated by Django 6.0.8 on 2026-09-05 06:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_businessupgradebankaccount_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employeeworkingschedule',
            name='unique_owner_schedule_slot',
        ),
        migrations.RemoveConstraint(
            model_name='employeeworkingschedule',
            name='unique_employee_schedule_slot',
        ),
        migrations.AddConstraint(
            model_name='employeeworkingschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('owner__isnull', False)), fields=('owner', 'day_of_week', 'slot_type'), name='unique_owner_schedule_slot'),
        ),
        migrations.AddConstraint(
            model_name='employeeworkingschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('employee__isnull', False), ('is_active', True)), fields=('employee', 'day_of_week', 'slot_type'), name='unique_employee_schedule_slot'),
        ),
    ]
