# Generated by Django 5.2.6 on 2026-09-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_business_upgrade_decision_email_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='rank',
            field=models.PositiveIntegerField(db_index=True, default=1, help_text="Priority rank used to order this business's services in search results and browsing. Higher rank is shown first. Currently set manually by admin; a future automated system may raise it based on search appearances, bookings, and clicks — this field is intentionally left unconstrained (no uniqueness, no max) so that future increment logic won't error."),
        ),
    ]
