# Generated by Django 6.0.8 on 2026-09-17 05:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_businessprofile_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessapplication',
            name='location',
            field=models.CharField(max_length=2000),
        ),
        migrations.CreateModel(
            name='BusinessPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_portfolio_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('starting_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('response_time', models.CharField(blank=True, choices=[('WITHIN_AN_HOUR', 'Within an hour'), ('WITHIN_A_FEW_HOURS', 'Within a few hours'), ('WITHIN_A_DAY', 'Within a day'), ('MORE_THAN_A_DAY', 'More than a day')], default='', max_length=20)),
                ('facebook_url', models.URLField(blank=True, default='')),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('twitter_url', models.URLField(blank=True, default='')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='business.businessprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessPortfolioFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faq_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='business.businessportfolio')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessPortfolioGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gallery_image_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(upload_to='business_portfolio/gallery/')),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='business.businessportfolio')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
