# Generated by Django 6.0.8 on 2026-09-25 06:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_businessportfolio_is_active_deletedbusinessidentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedbusinessidentity',
            name='deleted_business_identity_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
