# Generated by Django 6.0.8 on 2026-09-02 07:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_session_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('call_type', models.CharField(choices=[('AUDIO', 'Audio'), ('VIDEO', 'Video')], default='AUDIO', max_length=20)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('RINGING', 'Ringing'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('MISSED', 'Missed'), ('ENDED', 'Ended'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='INITIATED', max_length=20)),
                ('provider_call_id', models.CharField(blank=True, default='', help_text='External identifier from the 3rd party calling provider', max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
