# Generated by Django 6.0.8 on 2026-09-02 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calling_service', '0001_initial'),
        ('chat_service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_sessions', to='chat_service.conversation'),
        ),
        migrations.AddField(
            model_name='callsession',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_calls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['conversation', 'status'], name='calling_ser_convers_a461e0_idx'),
        ),
    ]
