# Generated by Django 6.0.8 on 2026-08-21 06:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('business', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('slot_type', models.CharField(choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('EVENING', 'Evening')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Snapshot of the service price at the time of booking.', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='accounts.address')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='business.businessprofile')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='business.employee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_employees', to='bookings.booking')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_assignments', to='business.employee')),
            ],
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='bookings_bo_user_id_69a5d5_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['business', 'status'], name='bookings_bo_busines_621743_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['scheduled_date'], name='bookings_bo_schedul_e26d39_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookingemployee',
            constraint=models.UniqueConstraint(fields=('booking', 'employee'), name='unique_booking_employee'),
        ),
    ]
