# Generated by Django 6.0.8 on 2026-09-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_bookingcompletionotp_otp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bookingcompletionotp',
            new_name='bookings_bo_booking_147844_idx',
            old_name='bookings_bo_booking_1a2b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='bookingcompletionotp',
            new_name='bookings_bo_instant_1b7b74_idx',
            old_name='bookings_bo_instant_4d5e6f_idx',
        ),
    ]
