# Generated by Django 6.0.8 on 2026-09-08 06:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('BOOKING_CREATED', 'Booking Created'), ('BOOKING_ACCEPTED', 'Booking Accepted'), ('BOOKING_REJECTED', 'Booking Rejected'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('EMPLOYEE_ASSIGNED', 'Employee Assigned'), ('SERVICE_STARTED', 'Service Started'), ('SERVICE_COMPLETED', 'Service Completed'), ('INSTANT_BOOKING_OFFER', 'Instant Booking Offer'), ('INSTANT_BOOKING_ACCEPTED', 'Instant Booking Accepted'), ('INSTANT_BOOKING_REJECTED', 'Instant Booking Rejected'), ('INSTANT_BOOKING_EXPIRED', 'Instant Booking Expired'), ('NO_PROVIDER_FOUND', 'No Provider Found'), ('NEW_CHAT_MESSAGE', 'New Chat Message'), ('INCOMING_CALL', 'Incoming Call'), ('CALL_MISSED', 'Call Missed'), ('CALL_ENDED', 'Call Ended')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='notificatio_recipie_86ea8b_idx')],
            },
        ),
    ]
